Traceback (most recent call last):
  File "/Users/sc3623/anaconda3/envs/engr131env/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/sc3623/anaconda3/envs/engr131env/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sc3623/anaconda3/envs/engr131env/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sc3623/anaconda3/envs/engr131env/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/sc3623/anaconda3/envs/engr131env/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/sc3623/anaconda3/envs/engr131env/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/sc3623/anaconda3/envs/engr131env/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import random
import matplotlib.pyplot as plt
from IPython.display import display, clear_output
from ipywidgets import widgets

def flip_coin():
    return random.choice(['Heads', 'Tails'])

def create_graphical_output(result):
    # Create a simple bar chart to represent the coin flip result
    fig, ax = plt.subplots()
    ax.bar(result, 1, color='skyblue')
    ax.set_ylim(0, 1)
    ax.set_xlim(-0.5, 1.5)
    ax.set_yticks([])
    ax.set_xticks([0, 1])
    ax.set_xticklabels(['Heads', 'Tails'])
    plt.title(f"Coin Flip Result: {result}")
    plt.show()

def on_button_clicked(b):
    guess = dropdown.value
    result = flip_coin()
    output.clear_output()
    with output:
        if guess == result:
            print(f"Correct! It was {result}.")
        else:
            print(f"Wrong! It was {result}.")
        create_graphical_output(result)

# Widgets
dropdown = widgets.Dropdown(options=['Heads', 'Tails'], description='Guess:')
button = widgets.Button(description='Flip Coin')
output = widgets.Output()

button.on_click(on_button_clicked)

# Display widgets
display(dropdown, button, output)

------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[7], line 2[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mrandom[39;00m
[0;32m----> 2[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m
[1;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mIPython[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdisplay[39;00m [38;5;28;01mimport[39;00m display, clear_output
[1;32m      4[0m [38;5;28;01mfrom[39;00m [38;5;21;01mipywidgets[39;00m [38;5;28;01mimport[39;00m widgets

[0;31mModuleNotFoundError[0m: No module named 'matplotlib'

